apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: web-app=noizysthlm/flask-app:latest
    argocd-image-updater.argoproj.io/update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/noizy-sthlm/argo-cd-multibranch-pipeline
    path: k8s-manifests
    targetRevision: dev
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: python-flask
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
